defmodule Database.Helpers.Language do
  @moduledoc """
  Language helper.
  """

  def all,
    do:
      (Countries.all()
       |> Enum.map(& &1.languages_spoken)
       |> List.flatten()
       |> Enum.reject(&is_nil/1)
       |> Enum.uniq()) ++ nil

  # TODO: Decomplex this function
  def convert(three) do
    case three do
      "arb" -> "ar"
      "pes" -> "fa"
      # "uig" -> "ug"
      "urd" -> "ur"
      "azj" -> "az"
      "bel" -> "be"
      "bos" -> "bs"
      "bul" -> "bu"
      "kaz" -> "kk"
      "khk" -> "mn"
      "kir" -> "ky"
      "koi" -> "kv"
      "mkd" -> "mk"
      "rus" -> "ru"
      "srp" -> "sr"
      "tat" -> "tt"
      "tgk" -> "tg"
      "tuk" -> "tk"
      "ukr" -> "uk"
      "uzn" -> "uz"
      "bho" -> "bh"
      "hin" -> "hi"
      "mag" -> "bh"
      "mai" -> "bh"
      "mar" -> "mr"
      "nep" -> "ne"
      "amh" -> "am"
      "tir" -> "ti"
      "heb" -> "he"
      "ydd" -> "yi"
      # "afr" -> "af"
      "lav" -> "lv"
      "deu" -> "de"
      "nno" -> "nn"
      "hrv" -> "hr"
      # "src" -> "sc"
      # "ayr" -> "ay"
      "lit" -> "lt"
      # "knc" -> ##"kr"
      # "run" -> "rn"
      "est" -> "et"
      # "toi" -> "to"
      # "lug" -> "lg"
      # "ssw" -> "ss"
      "ita" -> "it"
      # "xho" -> "xh"
      "swe" -> "sv"
      # "sna" -> "sn"
      # "slk" -> "sk"
      "dan" -> "da"
      # "slv" -> "sl"
      # "sun" -> "su"
      # "glg" -> "gl"
      # "yor" -> "yo"
      "nld" -> "nl"
      # "hat" -> "ht"
      "fra" -> "fr"
      # "sag" -> "sg"
      # "kng" -> "kg"
      # "bam" -> "bm"
      # "als" -> "sq"
      # "tso" -> "ts"
      "por" -> "pt"
      "hun" -> "hu"
      # "aka" -> "ak"
      # "tsn" -> "tn"
      # "ndo" -> "ng"
      # "uzn" -> "uz"
      # "hau" -> "ha"
      # "ind" -> "id"
      # "srp" -> "sr"
      "eng" -> "en"
      # "tgl" -> "tl"
      # "epo" -> "eo"
      # "tuk" -> "tk"
      # "nso" -> "st"
      # "bos" -> "bs"
      # "zul" -> "zu"
      # "uig" -> "ug"
      # "som" -> "so"
      # "jav" -> "jv"
      # "cat" -> "ca"
      "spa" -> "es"
      # "ewe" -> "ee"
      "nob" -> "nb"
      "fin" -> "fi"
      "ron" -> "ro"
      # "wol" -> "wo"
      # "ibo" -> "ig"
      # "tur" -> "tr"
      "ces" -> "cs"
      # "vie" -> "vi"
      # "nya" -> "ny"
      # "kin" -> "rw"
      "pol" -> "pl"
      # "sot" -> "st"
      # "lin" -> "ln"
      _ -> nil
    end
  end
end
