name: Elixir CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1
        id: versions
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{ steps.versions.outputs.elixir }}
          otp-version: ${{ steps.versions.outputs.erlang }}
          experimental-otp: true
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.versions.outputs.nodejs }}
      - name: Setup Rust toolchain
        uses: hecrj/setup-rust-action@v1.3.1
      - name: Install Dependencies
        run: mix deps.get
      - name: Install node dependencies for main subapp
        run: yarn
        working-directory: ./apps/main/assets
